Feat/#9 챔피언 좋아요/싫어요 삭제
gnimty/backend-community-service pull request #13
Opened 2023-10-23 08:34 UTC by kariskan

추가로, 챔피언 운용법 조회 시 자신이 수행한 좋아요/싫어요도 조회

2023-10-23 10:17 UTC, janguni approved these changes

2023-10-24 01:24 UTC, so1omon requested changes

2023-10-24 01:24 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/ChampionCommentsLikeService.java
> +		checkValidation(championId, championComments);
doChampionCommentsLike에서 championId를 ChampionCommentsLikeServiceRequest로만 받는 게 아니라 분리해서 받은 이후에 두 ID값이 같은지 비교까지 하시는 이유가 궁금합니다.

2023-10-24 01:24 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/global/interceptor/TokenAuthInterceptor.java
> +			}
테스트용으로 열어 두신 건가요?

2023-10-24 01:24 UTC, so1omon commented on src/main/resources/application.yml
이파일 application-local.yml로 분리한 다음에 gitignore에 추가하는 것도 좋아 보입니다.

2023-10-24 05:27 UTC, kariskan commented on src/main/java/com/gnimty/communityapiserver/global/interceptor/TokenAuthInterceptor.java
> +			}
이 부분은 챔피언 운용법 "조회" 시에만 해당되는건데 챔피언 운용법 조회는 로그인을 하지 않아도 조회가 가능해야하기 때문입니다.

2023-10-24 05:28 UTC, kariskan commented on src/main/resources/application.yml
나눈 뒤에 따로 말씀드리겠습니다!

2023-10-24 05:36 UTC, kariskan commented on src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/ChampionCommentsLikeService.java
> +		checkValidation(championId, championComments);
championId를 path variable로 받은 이유는 RESTful한 api를 위해서 자원의 경로를 나타낸 것입니다. 그리고 검증을 댓글 소속 여부를 확인해야 합니다.

2023-10-24 05:50 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/ChampionCommentsLikeService.java
> +		checkValidation(championId, championComments);
> championId를 path variable로 받은 이유는 RESTful한 api를 위해서 자원의 경로를 나타낸 것입니다. 

이 부분은 이해가 갔는데

> 그리고 "n번 챔피언에 m번 댓글이 없는 경우" 등을 검증하기위해 댓글 소속 여부를 확인해야 합니다.

이 부분은 어떤 상황인지 잘 이해가 가지 않습니다. 댓글 소속 여부를 따진다는게 한 회원이 중복해서 댓글을 올리지 못한다는 말씀이신가요?

2023-10-24 05:51 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/global/interceptor/TokenAuthInterceptor.java
> +			}
Spring Security 기반 Role을 사용 못해서 우회하신 거죠?

2023-10-24 05:52 UTC, so1omon commented on src/main/resources/application.yml
아아 따로 말씀 안하셔도, 파일 두개가 있으면 application-local.yml이 application.yml  내의 local 환경보다 우선순위를 가질 거에요. application-local.yml 이름으로 gitignore에만 등록하셔도 될 듯 합니다.

2023-10-24 05:58 UTC, kariskan commented on src/main/java/com/gnimty/communityapiserver/global/interceptor/TokenAuthInterceptor.java
> +			}
네 그렇습니당

2023-10-24 05:59 UTC, kariskan commented on src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/ChampionCommentsLikeService.java
> +		checkValidation(championId, championComments);
1번 챔피언에 댓글id가 1, 2, 3만 존재하는데 /community/champions/1/comments/4 라고 요청한다면 당연히 예외처리해야 하지 않을까요?

2023-10-24 07:15 UTC, so1omon approved these changes

2023-10-24 07:15 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/ChampionCommentsLikeService.java
> +		checkValidation(championId, championComments);
아 이해했습니다

2023-10-24 07:17 UTC, merged