Config/#148 embedded db test
gnimty/backend-community-service pull request #153
Opened 2024-02-05 04:07 UTC by janguni

- test 동작 테스트 완료
- application.yml 에서 test profiles 제거

2024-02-05 04:37 UTC, kariskan commented on .github/workflows/main.yml
>          run: ./gradlew test
여기까지 지우고 Build with Gradle에서 ```-x test``` 부분을 빼도 될 것 같네요.

2024-02-05 04:40 UTC, kariskan requested changes
확인 부탁드립니다.

2024-02-05 04:40 UTC, kariskan commented on .github/workflows/main.yml
>          run: ./gradlew test
여기까지 지우고 Build with Gradle에서 ```-x test``` 부분을 빼도 될 것 같네요.

2024-02-05 04:40 UTC, kariskan commented on src/test/resources/application-test.yml
> +      port: 0
포트 0으로 하신 이유가 있나요?

2024-02-05 04:40 UTC, kariskan commented on src/test/resources/application-test.yml
> +      defer-datasource-initialization: true
맨 마지막줄은 초기 데이터 집어넣을때 사용하는건데 없어도 될 것 같습니다!

2024-02-05 05:04 UTC, so1omon commented on .github/workflows/main.yml
>          run: ./gradlew test
그러게요 ./gradlew build -x test 이부분 test 실행안하는 옵션 빼지 않았었나요?

2024-02-05 05:04 UTC, so1omon commented on build.gradle
> +
이거는 왜빠지는거에요?

2024-02-05 05:05 UTC, kariskan commented on build.gradle
> +
아래 ```testImplementation 'de.flapdoodle.embed:de.flapdoodle.embed.mongo'``` 있습니다

2024-02-05 08:49 UTC, janguni commented on src/test/resources/application-test.yml
> +      port: 0
27017로 하면 local에서 테스트할 때 실패해서 못쓰고, 테스트할 때는 사용하고 있지 않은 포트를 랜덤으로 사용하는게 적절한 것 같아서 0으로 설정했습니다.

2024-02-05 08:50 UTC, janguni commented on src/test/resources/application-test.yml
> +      defer-datasource-initialization: true
네!

2024-02-05 10:57 UTC, kariskan approved these changes

2024-02-06 09:58 UTC, so1omon approved these changes

2024-02-06 13:57 UTC, merged