refactor: 채팅 서비스 날짜 타입 변경 후 테스트 완료
gnimty/backend-community-service pull request #160
Opened 2024-02-13 15:05 UTC by janguni

- 채팅 서비스의 날짜 타입 변경
Date -> Instant으로 변경하면서 밀리초까지 저장이 가능해짐

2024-02-14 11:40 UTC, kariskan requested changes
확인 부탁드립니다.

2024-02-14 11:40 UTC, kariskan commented on src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepositoryImpl.java
> +		Instant now = Instant.now(Clock.system(ZoneId.of("Asia/Seoul")));
application 최상단 클래스에서 @PostConstruct로 TimeZone 세팅 하면 이후 서비스 코드에서 따로 세팅 안해도 될 것 같습니다.

```
public class CommunityapiserverApplication {

	public static void main(String[] args) {
		SpringApplication.run(CommunityapiserverApplication.class, args);
	}

	@PostConstruct
	void setUp() {
		TimeZone.setDefault(TimeZone.getTimeZone("Asia/Seoul"));
	}
}
```

2024-02-14 11:40 UTC, kariskan commented on src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/ChatDto.java
> +	private Instant sendDate;
LocalDateTime으로 하면 되지 않나요?

2024-02-14 11:40 UTC, kariskan commented on src/main/java/com/gnimty/communityapiserver/global/utils/InstantKoreaTimeUtil.java
> +    public static Instant getNow() {
이 부분도 Timezone 세팅하고 LocalDateTime.now() 하면 될 것 같네요.

2024-02-14 16:22 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepositoryImpl.java
> +		Instant now = Instant.now(Clock.system(ZoneId.of("Asia/Seoul")));
이거 timezone 세팅 한 이후에 몽고디비에서 utc time으로 저장하는지 local time으로 저장하는지 확인해봐야 할거에요

2024-02-14 16:22 UTC, so1omon approved these changes

2024-02-19 02:26 UTC, so1omon approved these changes

2024-02-19 06:57 UTC, kariskan approved these changes

2024-02-19 06:58 UTC, merged