feat/#24 사용자 차단상태, 접속상태 용어 명확화, chatService 마무리
gnimty/backend-community-service pull request #25
Opened 2023-10-26 04:14 UTC by janguni

- 차단 상태, 접속 상태 용어 분리 
- chatService 남은 부분 구현
     채팅 저장
     readCount update
     isBlock() 리펙토링

2023-10-26 08:43 UTC, kariskan approved these changes

2023-10-26 10:15 UTC, so1omon requested changes

2023-10-26 10:15 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
> +			});
이부분 나중에 개선의 여지는 있어 보입니다.

2023-10-26 10:15 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
> +		return other;
이거 굳이 별도 메소드로 추출하신 이유가 있나요? inline variable처리하면 한 줄로도 충분히 명확하게 표현할 수 있을것 같은디

2023-10-27 06:03 UTC, so1omon approved these changes

2023-10-27 13:04 UTC, janguni commented on src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
> +			});
예시 부탁드립니다!

2023-10-27 13:04 UTC, janguni commented on src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
> +		return other;
예시 부탁드립니다!

2023-10-28 01:03 UTC, merged