feat/#42 채팅 읽는 로직 추가 및 MessageRequest 추가
gnimty/backend-community-service pull request #45
Opened 2023-11-05 05:56 UTC by janguni

- 채팅 읽는 로직 추가

           1. 채팅 전송 시
             상대방이 채팅방에 접속중이라면 채팅 저장 시 readCnt=0으로 저장, 그렇지 아니면 readCnt=1으로 저장
           2. 채팅방 접속 시 (채팅방을 클릭해서 들어감)
             상대방이 보낸 채팅의 readCnt update
       
          - 채팅방에 접속 중인지 아닌지 확인하기 위해 OnlineInChatRoomManager 생성
             1) 필드 userCurrentlyInChatRooms: 사용자와 현재 접속중인 채팅방No 저장
             2) 필드 userKeysCurrentlyWithChatRooms: Map<사용자Id, List 채팅방No> 저장
                   용도: 웹소켓이 끊겼을 경우 userCurrentlyInChatRooms에서  해당 사용자를 포함한 객체 제거

- MessageRequest 추가
     채팅방 나가기, 채팅 보내기 핸들러를 합치기 위함

2023-11-05 07:21 UTC, kariskan approved these changes

2023-11-07 11:06 UTC, so1omon requested changes
답변 부탁드려요!

2023-11-07 11:06 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
> +	}
요청경로가 갑자기 왜이렇게 많아졌나요?? 요청 dto에 type으로 넣어서 구분하기로 하지 않앗나요..?

2023-11-07 11:06 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
> +	}
유저가 /chatRoom이 아닌 enter_chatRoom와 vacate_chatRoom 구독정보를 통해 계속 데이터를 주고받나요?? @SubscribeMapping이 REST API처럼 동작한다는 사실은 말씀해주셨지만 불필요한 구독정보가 많아질 것 같습니다.

2023-11-07 11:06 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/global/constant/MessageRequestType.java
> +}
이거 채팅방 체크도 수행할 수 있어야 하지 않아요?

2023-11-07 11:06 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/global/constant/MessageResponseType.java
Constant definition은 어절별로 끊어서 underscore로 구분해주면 좋을 것 같습니다.

2023-11-07 11:06 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/global/connect/OnlineInChatRoomManager.java
> +    private List<UserCurrentlyInChatRoom> userCurrentlyInChatRooms = new LinkedList<>();
LinkedList를 채택해서 얻는 이점이 무엇인가요?

2023-11-07 11:06 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/global/connect/OnlineInChatRoomManager.java
이 친구 역할이 무엇인가요>...?

2023-11-08 04:58 UTC, janguni commented on src/main/java/com/gnimty/communityapiserver/global/connect/OnlineInChatRoomManager.java
만약, A사용자와 B사용자가 모두 채팅방 안에서 대화중인 상황에서 B가 A에게 채팅을 하나 보내면
채팅방 목록의 읽지않은 메세지가 +1이 되는 상황이 생겨버리게 돼서요.
그래서 사용자가 현재 어떤 채팅방을 열어놓고 있는지 확인해야 해서 만들었어요.

그런데 솔민님 말처럼 각각 사용자가 하나의 창만 열어놓으면 프론트에서 처리할 수 있을 것 같기도 한데,
만약 A사용자가 3개의 창을 열어놓았을 때 하나는 B사용자와 대화하는 창이고 나머지는 다른 사용자와 대화하는 창을 열어놓은 상태에서
B사용자가 A사용자에게 채팅을 하나 보내면
B사용자가 아닌 다른 사용자와 대화하는 창에서는 (읽지않은 메세지 +=1)을 프론트에서 제어할 수 있는 방법이 없을 것 같아요.

2023-11-08 04:59 UTC, janguni commented on src/main/java/com/gnimty/communityapiserver/global/connect/OnlineInChatRoomManager.java
> +    private List<UserCurrentlyInChatRoom> userCurrentlyInChatRooms = new LinkedList<>();
삭제가 빈번해서 LinkedList로 했습니다.

2023-11-08 05:00 UTC, janguni commented on src/main/java/com/gnimty/communityapiserver/global/constant/MessageResponseType.java
넵

2023-11-08 05:00 UTC, janguni commented on src/main/java/com/gnimty/communityapiserver/global/constant/MessageRequestType.java
> +}
채팅방 체크가 어떤거죠??

2023-11-08 05:00 UTC, janguni commented on src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
> +	}
아 그렇겠네요. 합치겠습니다!

2023-11-08 06:04 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/global/constant/MessageRequestType.java
> +}
위에서 언급한 enter_chatRoom의 기능이 될 것 같아요

2023-11-08 06:09 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/global/connect/OnlineInChatRoomManager.java
하나의 탭에서 여러 창을 띄우는 상황을 생각하신다면 그런 상황은 발생하지 않습니다. 선택된 채팅방의 내역조회 및 채팅만 보낼 수 있어요.
만약 멀티 탭 환경에서의 다중 창을 띄워 놓은 상황을 생각하셨다면, 브라우저별로 각각 다른 프론트 코드가 작동할 텐데 문제가 되는 부분이 있을까요?

2023-11-08 10:40 UTC, janguni commented on src/main/java/com/gnimty/communityapiserver/global/connect/OnlineInChatRoomManager.java
(readOtherChats을 성능을 개선해서 채팅을 보낼 때마다 호출하기로 결론남)

2023-11-11 03:45 UTC, janguni reviewed
채팅 읽는 로직 변경함.

MessageRequestType으로 READ를 받으면 readOtherChats 수행 후
해당 사용자에게 MessageResponseType으로 READ_CHATS를 채팅방id와 함께 전송

2023-11-11 06:20 UTC, so1omon approved these changes

2023-11-11 06:24 UTC, merged