Feat/#10 최근 플레이 한 소환사 추천 조회
gnimty/backend-community-service pull request #47
Opened 2023-11-06 08:13 UTC by kariskan

this closes #10

2023-11-07 07:54 UTC, so1omon requested changes

2023-11-07 07:54 UTC, so1omon commented on src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountService.java
> +	}
이거 이렇게되면 쿼리가 불필요하게 많이 나가지 않나요?

2023-11-07 09:51 UTC, janguni approved these changes

2023-11-08 02:42 UTC, kariskan commented on src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountService.java
> +	}
[이거](https://github.com/gnimty/backend-community-service/issues/49) 테스트 이후에 바로 진행할건데 여기서 개선하겠습니당

2023-11-08 06:03 UTC, so1omon approved these changes

2023-11-08 06:03 UTC, merged